import Link from "next/link";
import { withDatabase } from "@/lib/db";
import { listBundles } from "@/lib/repository";
import { filtersFrom } from "@/lib/http";
import { Cards } from "@/components/cards";
import { Icon } from "@/components/icon";
export default async function Home({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const query = new URLSearchParams(); for (const [key, value] of Object.entries(raw)) if (typeof value === "string") query.set(key, value);
  let error = ""; let result: Awaited<ReturnType<typeof listBundles>> = { items: [], hasMore: false, page: 1 };
  try { result = await withDatabase(pool => listBundles(pool, filtersFrom(query))); }
  catch { error = "社区暂时无法连接，请稍后重试。"; }
  const filtered = ["q", "application", "modelId", "brand"].some(k => query.get(k));
  function pageHref(page: number) { const p = new URLSearchParams(query); p.set("page", String(page)); return "/?" + p.toString() + "#explore"; }
  return <><section className="hero"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="status-dot" />为你的每一块屏幕</div><h1>好画面，<br />从一份<span>好配置</span>开始。</h1><p>从专注办公到沉浸游戏，发现与你的显示器相配的参数组合。调出喜欢的画面，也把它分享出去。</p><div className="hero-actions"><a className="button primary" href="#explore">发现屏幕配方 <Icon name="arrow" size={18} /></a><a className="button subtle" href="https://github.com/chuanjianghe1024-cmd/FluentControl/actions/workflows/build.yml"><Icon name="download" size={18} />获取 Windows 客户端</a></div><div className="hero-footnote"><span><Icon name="check" size={14} /> 多屏场景</span><span><Icon name="check" size={14} /> 按型号查找</span><span><Icon name="check" size={14} /> 批量导入</span></div></div>
    <div className="hero-visual" aria-label="桌面控制面板示意"><div className="orb orb-one" /><div className="orb orb-two" /><div className="display-outline back"><div /></div><div className="display-outline front"><div className="wallpaper"><span /><span /><span /></div><i /></div><div className="floating-control"><div className="floating-top"><span className="control-icon"><Icon name="sun" size={18} /></span><strong>刚刚好的日常</strong><small>界面示意</small></div><div className="demo-row"><span>整体亮度</span><i style={{ "--fill": "62%" } as React.CSSProperties} /><b>62</b></div><div className="demo-row"><span>整体对比度</span><i style={{ "--fill": "75%" } as React.CSSProperties} /><b>75</b></div><div className="floating-bottom"><span className="status-dot" />工作与生活，各有自己的画面。</div></div><span className="visual-caption">ONE DESK. YOUR SETTINGS.</span></div>
  </section><section className="explore" id="explore"><div className="section-heading"><div><div className="eyebrow">COMMUNITY PRESETS</div><h2>找到适合你的配置</h2></div><span className="muted">以配置包分享，按场景使用</span></div>
    <form className="filters" action="/#explore"><label className="search-field"><Icon name="search" /><input name="q" defaultValue={query.get("q") || ""} placeholder="搜索配置名称或说明" aria-label="搜索配置名称或说明" maxLength={120} /></label><div className="filter-fields"><label>应用 / 游戏<input name="application" defaultValue={query.get("application") || ""} placeholder="例如 Photoshop" maxLength={80} /></label><label>显示器型号<input name="modelId" defaultValue={query.get("modelId") || ""} placeholder="型号名称或 PnP 码" maxLength={128} /></label><label>品牌<input name="brand" defaultValue={query.get("brand") || ""} placeholder="例如 Dell、Huawei" maxLength={80} /></label><button className="button primary" type="submit">筛选 <Icon name="sliders" size={16} /></button></div></form>
    <div className="results-heading"><span>{filtered ? "筛选结果" : "最近更新"}</span>{filtered ? <Link className="text-button" href="/#explore">清除筛选</Link> : <span className="muted">每一种习惯，都值得一个专属场景。</span>}</div>
    {error ? <div className="empty-state"><Icon name="monitor" size={40} /><h3>{error}</h3><Link className="button subtle" href="/#explore">重新加载</Link></div> : result.items.length ? <Cards items={result.items} /> : <div className="empty-state"><span className="empty-icon"><Icon name={filtered ? "search" : "layers"} size={36} /></span><h3>{filtered ? "暂时没有匹配的配置" : "第一份好配置，从你开始"}</h3><p>{filtered ? "减少一个筛选条件，或者试试显示器的型号名称。" : "把已经调好的办公、游戏或夜间场景分享出来。"}</p><Link className="button subtle" href={filtered ? "/#explore" : "/publish"}>{filtered ? "查看全部配置" : "分享我的配置"}<Icon name="arrow" size={16} /></Link></div>}
    {(result.page > 1 || result.hasMore) && <nav className="pagination" aria-label="分页">{result.page > 1 && <Link className="button subtle" href={pageHref(result.page - 1)}>上一页</Link>}<span>第 {result.page} 页</span>{result.hasMore && <Link className="button subtle" href={pageHref(result.page + 1)}>下一页</Link>}</nav>}
  </section><section className="how-it-works"><div><span>01</span><h3>找到你的屏幕</h3><p>按品牌、型号和正在使用的应用，缩小选择范围。</p></div><div><span>02</span><h3>预览，再带走</h3><p>查看每个场景的参数，下载整包，或复制导入链接。</p></div><div><span>03</span><h3>调成自己的样子</h3><p>导入后匹配本机显示器，确认参数，再应用喜欢的场景。</p></div></section></>;
}
